<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>71f4a128-3fe5-4569-ad1e-90ff96d9e8f8</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>..\..</DockerfileContext>
		<Version>1.0.0</Version>
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<FileVersion>1.0.0.0</FileVersion>
	</PropertyGroup>

	<ItemGroup>
	  <Content Remove="Translations\Health.en.json" />
	  <Content Remove="Translations\Health.fr.json" />
	  <Content Remove="Translations\Health.nl.json" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="Translations\Health.nl.json" />
	  <None Include="Translations\Health.en.json" />
	  <None Include="Translations\Health.fr.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="FluentValidation" Version="12.1.1" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
	</ItemGroup>

</Project>
